// react/src/App.jsx
import Card from "./components/Card";
import Details from "./components/Details";
import DataContainer from "./components/DataContainer";
// import useData from "./components/useData";

function App() {
    // const { data } = useData();

    return (
        <>
            <DataContainer>
                <Card />
                <Details />
            </DataContainer>
            {/* <Card data={data} />
            <Details data={data} /> */}
        </>
    );
}

export default App;

// vue/src/App.vue
<script setup>
// import DataContainer from "./components/DataContainer.vue";
import Card from "./components/Card.vue";
import Details from "./components/Details.vue";
import useData from "./components/useData";

const { data } = useData();
</script>

<template>
    <!-- <DataContainer v-slot="{ data }"> -->
    <Card :data="data" />
    <Details :data="data" />
    <!-- </DataContainer> -->
</template>
